
name: 'Terraform Destroy'

on:
  workflow_dispatch:
    inputs:
        confirm_destroy:
          description: 'Type "yes" to confirm destruction'
          required: true
          default: 'no'

jobs:
  terraform:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    environment: development
    
    permissions:
      contents: read 

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}


    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform/

    - name: Terraform Plan
      run: terraform plan -destroy -input=false
      working-directory: ./terraform/

    - name: Terraform Destroy
      if: github.event.inputs.confirm_destroy == 'yes'
      run: terraform destroy -auto-approve -input=false
      working-directory: ./terraform/

    - name: Warn if Destroy Not Confirmed
      if: github.event.inputs.confirm_destroy != 'yes'
      run: |
        echo "Terraform destroy was skipped because 'yes' was not provided as confirmation."
        echo "No resources were destroyed.
      working-directory: ./terraform/
